sudo: false

language: php

php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

before_insall:
  - travis_retry composer self-update

jobs:
  - stage: Test
    install:
      - travis_retry composer install --no-interaction --prefer-dist
    script:
      - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
  - stage: Code Quality
    install:
      - travis_retry composer install --no-interaction --prefer-dist
    script:
      - vendor/bin/phpcs
